<a href="https://colab.research.google.com/github/AndrewKostin/TUII_2019/blob/master/umap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from umap import UMAP
from sklearn.preprocessing import StandardScaler

from google.colab import files, drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
path = '/content/drive/My Drive/colab/ONTI_FINAL/{}'

train = pd.read_csv(path.format('transactions_train.csv'))
test = pd.read_csv(path.format('transactions_test.csv'))

target = pd.read_csv(
    path.format('train_target.csv'),
    index_col='client_dk')
target.columns = target.columns.astype(int)

transactions = pd.concat([train, test]).reset_index(drop=True)

In [0]:
big = transactions.groupby('client_dk').amount.agg(['sum', 'count', 'mean', 'min', 'max', 'std']).fillna(0)

In [0]:
v_c = transactions.small_group.value_counts(normalize=True)*100
del_group = v_c[v_c < 0.001].index
transactions = transactions[~transactions.small_group.isin(del_group)]

In [5]:
%%time
# data = transactions.groupby(['client_dk', 'small_group', transactions.trans_date//30]).amount.count().unstack().unstack().fillna(0)
data = transactions.groupby(['client_dk', 'small_group']).amount.count().unstack().fillna(0)

scaler = StandardScaler()
umap = UMAP(n_neighbors=5, n_components=2, min_dist=0.2)#, metric='cosine')
data_umap = umap.fit_transform(scaler.fit_transform(data))

big = big.join(pd.DataFrame(data_umap))

/usr/local/lib/python3.6/dist-packages/numba/typed_passes.py:293: NumbaPerformanceWarning:
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../usr/local/lib/python3.6/dist-packages/umap/rp_tree.py", line 135:
@numba.njit(fastmath=True, nogil=True, parallel=True)
def euclidean_random_projection_split(data, indices, rng_state):
^

  state.func_ir.loc))
/usr/local/lib/python3.6/dist-packages/umap/nndescent.py:92: NumbaPerformanceWarning:
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../usr/local/lib/python3.6/dist-packages/umap/utils.py", line 409:
@numba.njit(parallel=True)
def build_candidates(current_graph, n_vertices, n_neighbors, max_candidates, rng_state):
^

  current_graph, n_vertices, n_neighbors, max_candidates, rng_state
/usr/local/lib/python3.6/dist-packages/numba/typed_passes.py:293: NumbaPerformanceWarning:
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../usr/local/lib/python3.6/dist-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  state.func_ir.loc))
/usr/local/lib/python3.6/dist-packages/umap/spectral.py:229: UserWarning: Embedding a total of 3 separate connected components using meta-embedding (experimental)
  n_components

CPU times: user 1min 45s, sys: 1.42 s, total: 1min 46s
Wall time: 1min 37s

In [0]:
transactions = transactions[transactions.small_group.isin(target.columns)]

In [13]:
transactions.small_group.value_counts()

45    358404
41    344523
27    231076
32    178963
73     68651
67     39381
88     36163
81      7410
Name: small_group, dtype: int64

In [0]:
transactions = transactions.sort_values(by=['client_dk', 'trans_date'])

add = []
for group in transactions.small_group.unique():
    mask = transactions.small_group == group
    t = transactions.loc[mask, ['client_dk', 'trans_date']]
    time_interval = t.trans_date - t.trans_date.shift()
    
    # эти 2 строки заполняют первые значения нанами. 
    # это нужно потому-что в этих значениях интервал между первой покупкой нового глиента и последней покупкой прошлого клиента
    new_client = (t.client_dk - t.client_dk.shift()) > 0
    time_interval.mask(new_client, inplace=True)

    time_interval = time_interval.groupby(t.client_dk).agg(['min', 'max', 'std', 'mean'])
    time_interval.columns += f'_time_delta_{group}'
    add.append(time_interval)

big = big.join(pd.concat(add, axis=1).fillna(-1))

In [0]:
# add = transactions.groupby(['client_dk', 'small_group', transactions.trans_date//30]).amount.agg(['sum', 'count', 'mean', 'min', 'max', 'std']).unstack().fillna(0)
# add.columns = [f'month_{col1}_{col2}' for col1, col2 in add.columns]

In [9]:
%%time
# данные по цене покупок в каждой группе
add = transactions.groupby(['client_dk', 'small_group']).amount.agg(['sum', 'count', 'mean', 'min', 'max', 'std']).unstack().fillna(0)
add.columns = [f'{col1}_{col2}' for col1, col2 in add.columns]
big = big.join(add)

# тоже самое по датам
add = transactions.groupby(['client_dk', 'small_group']).trans_date.agg(['mean', 'min', 'max', 'std']).unstack().fillna(0)
add.columns = [f'date_{col1}_{col2}' for col1, col2 in add.columns]
big = big.join(add)

# цена покупок по месяцам 
add = transactions.groupby(['client_dk', transactions.trans_date//30]).amount.agg(['sum', 'count', 'mean', 'min', 'max', 'std']).unstack().fillna(0)
add.columns = [f'month_{col1}_{col2}' for col1, col2 in add.columns]
big = big.join(add)

CPU times: user 2.21 s, sys: 63.9 ms, total: 2.27 s
Wall time: 2.27 s

In [10]:
big

                   sum  count  ...  month_std_11  month_std_12
client_dk                      ...
0            21590.476    774  ...      0.000000     11.316217
1            39375.929   1251  ...     27.804335      1.060592
2            40328.909   1514  ...     14.030348     62.715230
3            49014.558    925  ...      0.000000     75.589107
4            52078.639   1412  ...      0.000000     18.140577
...                ...    ...  ...           ...           ...
49995      1281898.582    715  ...  26215.273167    328.419280
49996        33749.300    918  ...     14.698629     11.258031
49997        34261.030   1316  ...     24.449844     11.785072
49998         9380.482    657  ...      0.000000      0.000000
49999        16636.180    783  ...     64.462734      8.356017

[50000 rows x 198 columns]

In [0]:
big.to_csv(path.format('big.csv'))